### ISSUE TITLE
Audio output and camera switch

### ISSUE THREAD

**Issue by dragospanoiu** [ISBX/apprtc-ios#10]
Is there any way to implement the audio output selector (speaker, phone) and the camera switch (front, rear)?

Thanks.

**Comment by a-athaullah** [comment]
@dragospanoiu : i already create pull request for swap camera functionality in this commit, please check on pull request. hope it will be usefull.

**Comment by coolwr** [comment]
@dragospanoiu, implemented default to speakerphone and added methods to disable/enable speakerphone.
