### ISSUE TITLE
Local video not showing and not visible in other end in Iphone X and iphone 6s 

### ISSUE THREAD

**Issue by bhoomesh950** [ISBX/apprtc-ios#120]
please help me

**Comment by bhoomesh950** [comment]
solved

**Comment by pratyushpratiksinha** [comment]
how? Even my remote view is not showing.

**Comment by NirajCapermint** [comment]
@bhoomesh950 how you fixed? any code of line you could provide. It will be helpful.

**Comment by Abhijit-Kayande** [comment]
@bhoomesh950 Can you please tell us how you solved this problem?
