### ISSUE TITLE
iOS to iOS device not working 

### ISSUE THREAD

**Issue by sourov2008** [ISBX/apprtc-ios#133]
I did not any change of your code, Just install in two iOS devices. Room connection is the success but there is no video or audio.
It is mentionable that iOS device to Andriod device, iOS device to Web, iOS device to simulator working fine .
Did you face same kind or similar kinds of problems?

**Comment by pratyushpratiksinha** [comment]
How you solved it? I have same error

**Comment by sourov2008** [comment]
I am sorry I could not solve this issue, rather I postponed this project. If you will have solved this issues please inform me.
