### ISSUE TITLE
iphone 5s doesn't support connection with last version of Mozilla firefox.

### ISSUE THREAD

**Issue by kos9kus** [ISBX/apprtc-ios#15]
I tested with iphone 5, it works, whereas iphone 5s doesn't work.
It seems like there are processor differences or perhaps there are some incompatibilities inside the firefox and the RTCLib.
I use a 42.0 firefox version.
By the way, works fine with the Opera.
Thanks

**Comment by coolwr** [comment]
Just tested on iPhone 6S with Firefox 42.0 and seems to be fine. I'll try to get my hands on an iPhone 5S. Try doing a `pod install` to get the latest libWebRTC.a library and see if that fixes the issue. Thanks!

**Comment by kos9kus** [comment]
Thank you! It helped me out
