### ISSUE TITLE
AppRTC demo can't link between two iphones, it's worked fine between on iphone and brower.

### ISSUE THREAD

**Issue by liuhuan1991** [ISBX/apprtc-ios#19]
I test it by use two iphones client, but it can't find the same room. How to use or set for two iphones?

**Comment by liuhuan1991** [comment]
It's OK, just the reason of the Fuck Great Firewall of China.

**Comment by shoaibhassanWhizpool** [comment]
Does iPhone or iPad use firewall.i am also unable to connect within iOS devices.
