### ISSUE TITLE
Support for one broadcaster and multiple viewers

### ISSUE THREAD

**Issue by evermeer** [ISBX/apprtc-ios#2]
I think WebRTC should be able to support one broadcaster with multiple viewers Like apps like Periscope and Meerkat are doing. With this SDK it looks like you can only join a room and initiate a one to one communication. I would like to have the possibility to just follow / watch a stream from a room. 

Is there a workaround with the current library to achieve this?
Is such functionality planned on the roadmap for this SDK? 
If I would want to implement this functionality in the SDK myself, how much would I need to change? Do you have any pointers about what to change where?

**Comment by kos9kus** [comment]
Hi, Are you working on this ? How are your things going ?
I'm going to implement the feature but so far I have an ongoing investigation only.

**Comment by evermeer** [comment]
I have switched to TLKWebRTC. It's not ideal either, but it sort of works now.

**Comment by kos9kus** [comment]
Do you provide a straight reference to that, please ??

**Comment by evermeer** [comment]
Have a look at these 2
https://github.com/otalk/TLKSimpleWebRTC
https://github.com/otalk/TLKWebRTC

**Comment by kos9kus** [comment]
Thank you so much!
