### ISSUE TITLE
Pods error - target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by royherma** [ISBX/apprtc-ios#21]
Getting this error when trying to install via pods:

```
Installing libjingle_peerconnection (11177.2.0)
[!] The 'Pods-Dabble' target has transitive dependencies that include static binaries: (/Users/royhermann/Desktop/Development/Dabble/Pods/libjingle_peerconnection/libjingle_peerconnection/libWebRTC.a)
```

Any ideas how to successfully install? 

Thanks

**Comment by royherma** [comment]
BTW - The way the pod is set up, is it suppose to work for Swift as well or only ObjC?

**Comment by KeChihYang** [comment]
I also got this problem. My podfile need install Socket.IO-Client-Swift which need "use_framework!" command, but if add use_framework! in podfile, it can not successfully install.

Only remove use_framework! from podfile, can be installed successfully.

Anyone know how to fix this problem?

**Comment by sushilthe** [comment]
I am trying to integrate the AppRTC pod in my project (https://github.com/sushilthe/webrtc-ios-swift) but including `use_frameworks!` in PodFile gives me the exact same error. 

Does anyone have the solution?

**Comment by a-athaullah** [comment]
I allready check on your project and run it on my xcode, it works well. So maybe you just need to update your pod.

**Comment by a-athaullah** [comment]
fyi: I just add "App Transport Security Settings" -> "Allow Arbitrary Loads" : "YES" in info.plist

**Comment by kumangdeal** [comment]
any solution ?

**Comment by stanchiang** [comment]
^bump

**Comment by coolwr** [comment]
Hi All, it might be a while before anyone on our side will be able to look into the "transitive dependency" error that occurs with the latest version of cocoa pods. Here's some guidance on this thread: https://github.com/ISBX/apprtc-ios/issues/39

**Comment by stanchiang** [comment]
got it. appreciate the quick followup.

**Comment by momosmile** [comment]
I also got this problem.please solution this problem？

**Comment by coolwr** [comment]
AppRTC upgraded to 1.0.3. For the `transitive dependencies that include static binaries` error when installing you can add the following to your `PodFile`

```
pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
```

**Comment by v-at-y** [comment]
Per https://github.com/CocoaPods/CocoaPods/issues/3289#issuecomment-313726321, the pre_install command post-cocapods 1.3.x should be:

    pre_install do |installer|
        # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
        Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    end

**Comment by marwendoukh** [comment]
You could install SocketIO with Carthage by adding this line to your `Cartfile` : 

`github "socketio/socket.io-client-swift"`

Then add the `Starscream` and `SocketIO` frameworks to your project.

**Comment by sansuba** [comment]
> Per [CocoaPods/CocoaPods#3289 (comment)](https://github.com/CocoaPods/CocoaPods/issues/3289#issuecomment-313726321), the pre_install command post-cocapods 1.3.x should be:
> 
> ```
> pre_install do |installer|
>     # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
>     Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
> end
> ```

this was helped to solve the issue. My pod version is 1.0.4
