### ISSUE TITLE
Getting Duplicate symbols issue when I integrate AppRTC with other third party files

### ISSUE THREAD

**Issue by Vidhyanand-K** [ISBX/apprtc-ios#3]
I am having pod file for different third party integration along with AppRTC. When I integrate AppRTC with other files it is getting Duplicate Symbols error.

Previously my project is fine with cocoa pods before integrating AppRTC. But after integrating it is getting errors. Please refer below link. It is getting conflicts with TwilioSDK and Socket Rocket.

Can u keep the steps for integrating AppRTC without use of cocoa pods. As libWebRTC.a is getting conflicts with other SDK's.

http://stackoverflow.com/questions/31052337/how-to-remove-duplicate-files-generated-through-cocoa-pods-in-ios

**Comment by coolwr** [comment]
We fixed some dependency issues in v1.0.2 around SocketRocket, which was compiled into the previous libWebRTC.a static library we were using. However, with the latest v1.0.2 we separated out the dependency to prevent these issues. 

```
pod 'AppRTC', '~>1.0.2'
```
