### ISSUE TITLE
 Showing Recent Errors Only clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by llongoria** [ISBX/apprtc-ios#65]
HI, Im getting this error someone know what is the problem:

Ld /Users/llongoria/Library/Developer/Xcode/DerivedData/AppRTC-anelwrjtwrbrmqdxkufqojcrsirc/Build/Products/Debug-iphoneos/AppRTC.app/AppRTC normal arm64
    cd /Users/llongoria/Documents/RTCOMM/ios-apps/apprtc-ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk -L/Users/llongoria/Library/Developer/Xcode/DerivedData/AppRTC-anelwrjtwrbrmqdxkufqojcrsirc/Build/Products/Debug-iphoneos -L/Users/llongoria/Documents/RTCOMM/ios-apps/apprtc-ios/Pods/libjingle_peerconnection -L/Users/llongoria/Documents/RTCOMM/ios-apps/apprtc-ios/Pods/libjingle_peerconnection/libjingle_peerconnection -L/Users/llongoria/Documents/RTCOMM/ios-apps/apprtc-ios/Lib -F/Users/llongoria/Library/Developer/Xcode/DerivedData/AppRTC-anelwrjtwrbrmqdxkufqojcrsirc/Build/Products/Debug-iphoneos -filelist /Users/llongoria/Library/Developer/Xcode/DerivedData/AppRTC-anelwrjtwrbrmqdxkufqojcrsirc/Build/Intermediates/AppRTC.build/Debug-iphoneos/AppRTC.build/Objects-normal/arm64/AppRTC.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.1 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/llongoria/Library/Developer/Xcode/DerivedData/AppRTC-anelwrjtwrbrmqdxkufqojcrsirc/Build/Intermediates/AppRTC.build/Debug-iphoneos/AppRTC.build/Objects-normal/arm64/AppRTC_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -lAppRTC -lSocketRocket -lWebRTC -lc -lc++ -licucore -lsqlite3 -lstdc++ -lstdc++.6 -framework AVFoundation -framework AudioToolbox -framework CFNetwork -framework CoreAudio -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework GLKit -framework OpenGLES -framework QuartzCore -framework Security -framework UIKit -framework VideoToolbox -lPods -Xlinker -dependency_info -Xlinker /Users/llongoria/Library/Developer/Xcode/DerivedData/AppRTC-anelwrjtwrbrmqdxkufqojcrsirc/Build/Intermediates/AppRTC.build/Debug-iphoneos/AppRTC.build/Objects-normal/arm64/AppRTC_dependency_info.dat -o /Users/llongoria/Library/Developer/Xcode/DerivedData/AppRTC-anelwrjtwrbrmqdxkufqojcrsirc/Build/Products/Debug-iphoneos/AppRTC.app/AppRTC

ld: library not found for -lAppRTC
clang: error: linker command failed with exit code 1 (use -v to see invocation)
![captura de pantalla 2016-09-23 a las 6 14 23 p m](https://cloud.githubusercontent.com/assets/1166207/18803843/a792a8f4-81b9-11e6-80ec-5692ee2ebd44.png)

**Comment by coolwr** [comment]
Open the AppRTC.xcworkspace instead of the project file to get all the dependencies.
