### ISSUE TITLE
Linking fails under XCode 8 

### ISSUE THREAD

**Issue by yoshikiohshima** [ISBX/apprtc-ios#66]
By just cloning the repository, opening the xcodeproj file and buidling fails on Mac OS Sierra with XCode 8.  I am afraid that this is actually an RTFM kind of question but can anybody shed a light on this?

-----
Ld /Users/ohshima/Library/Developer/Xcode/DerivedData/AppRTC-cccmzzkjdlyjqvaoisnlhyayvrnz/Build/Products/Debug-iphoneos/AppRTC.app/AppRTC normal arm64
    cd /Users/ohshima/src/apprtc-ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk -L/Users/ohshima/Library/Developer/Xcode/DerivedData/AppRTC-cccmzzkjdlyjqvaoisnlhyayvrnz/Build/Products/Debug-iphoneos -L/Users/ohshima/src/apprtc-ios/Pods/libjingle_peerconnection -L/Users/ohshima/src/apprtc-ios/Pods/libjingle_peerconnection/libjingle_peerconnection -L/Users/ohshima/src/apprtc-ios/Lib -F/Users/ohshima/Library/Developer/Xcode/DerivedData/AppRTC-cccmzzkjdlyjqvaoisnlhyayvrnz/Build/Products/Debug-iphoneos -filelist /Users/ohshima/Library/Developer/Xcode/DerivedData/AppRTC-cccmzzkjdlyjqvaoisnlhyayvrnz/Build/Intermediates/AppRTC.build/Debug-iphoneos/AppRTC.build/Objects-normal/arm64/AppRTC.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.1 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/ohshima/Library/Developer/Xcode/DerivedData/AppRTC-cccmzzkjdlyjqvaoisnlhyayvrnz/Build/Intermediates/AppRTC.build/Debug-iphoneos/AppRTC.build/Objects-normal/arm64/AppRTC_lto.o -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -lAppRTC -lSocketRocket -lWebRTC -lc -lc++ -licucore -lsqlite3 -lstdc++ -lstdc++.6 -framework AVFoundation -framework AudioToolbox -framework CFNetwork -framework CoreAudio -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework GLKit -framework OpenGLES -framework QuartzCore -framework Security -framework UIKit -framework VideoToolbox -lPods -framework WebRTC -Xlinker -dependency_info -Xlinker /Users/ohshima/Library/Developer/Xcode/DerivedData/AppRTC-cccmzzkjdlyjqvaoisnlhyayvrnz/Build/Intermediates/AppRTC.build/Debug-iphoneos/AppRTC.build/Objects-normal/arm64/AppRTC_dependency_info.dat -o /Users/ohshima/Library/Developer/Xcode/DerivedData/AppRTC-cccmzzkjdlyjqvaoisnlhyayvrnz/Build/Products/Debug-iphoneos/AppRTC.app/AppRTC

ld: library not found for -lAppRTC
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by coolwr** [comment]
You need to open the `AppRTC.xcworkspace` file instead of the xcodeproj. The workspace has the AppRTC pod dependency.
