### ISSUE TITLE
pod fail

### ISSUE THREAD

**Issue by black1997** [ISBX/apprtc-ios#71]
when use cocopads install the AppRTC,i can not sucess;
<img width="571" alt="dd5f8e59-750b-44f0-9e2c-36b99939abd8" src="https://cloud.githubusercontent.com/assets/15035749/20587901/f01b1a76-b24b-11e6-9a37-95bc6cd725b4.png">

**Comment by wenxin3262** [comment]
I have a repo working with pod that compiled directly from WebRTC source. [here](https://github.com/wenxin3262/WebRTC-iOS.git)

**Comment by coolwr** [comment]
Seems like a github error and unrelated to AppRTC.
