### ISSUE TITLE
Compile libWebRTC.a to include x86_64

### ISSUE THREAD

**Issue by Reedyuk** [ISBX/apprtc-ios#9]
Hi,
I tried to compile the webrtc stuff but i really couldnt work it out, even after a few days wasted on it. 
Please can you recompile the lib bundled with the cocoapod to handle the 64bit simulator too.

Thanks

**Comment by kos9kus** [comment]
We  should ask the host of this repository directly. It would be great if he wrote a tutorial, I wasted a lot of time too, in the end I couldn't compile properly.

**Comment by coolwr** [comment]
Hi All,

I just updated the repo with the latest libWebRTC.a dependency. We're now sourcing it from an automated build repository where they are frequently building from the latest WebRTC source. This latest update fixes several bugs from prior versions of libWebRTC as well as issues with connecting from iOS to Chrome 46.
